blogapp/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
	 url(r'^article/(?P<article_prikey>[\w]*)$', views.articlepage, name='article_page'),
	 url(r'^$', views.homepage, name='homepage'),
	 # url(r'^article/(?P<page>[\w]+-(?P<num>[\d]+))/$', views.test_page)
	url(r'^article/page-(?P<num>[\d]+)/$', views.test_page),
	# url(r'^article/(?P<article_prikey>[\w]*)/vote/$', views.vote, name='vote'),
	url(r'article/vote/$', views.vote_all_result, name='vote_all'),
	url(r'^upload/$', views.upload_file, name='upload'),
	url(r'^myarticle/$', views.myArticle, name='myArticle'),
	url(r'^myarticle/(?P<article_prikey>[\w]*)$', views.editArticle, name='editArticle'),
	# url(r'^download/(?P<file>[\w]+.*)$', views.download, name='download'),
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import blogapp.views as bv


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include(('blogapp.urls', 'blogapp'), namespace='blog')),
    url(r'^$', bv.homepage),
    url(r'^login/$', bv.login, name='login'),
    url(r'^register/$', bv.register, name='register'),
    url(r'logout/$', bv.logout, name='logout'),
    url(r'^download/(?P<file>.*)', bv.download, name='download'),
    url(r'^chatroom/$', bv.chatroom, name='chatroom')
]

blogapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.utils import timezone


class Article(models.Model):

		title = models.CharField(max_length=32, default="title", primary_key=True)
		content = models.TextField(null=True)
		release_time = models.DateTimeField('发布时间',default=timezone.now)
		last_edit_time = models.DateTimeField('最后修改', auto_now=True)
		counter = models.IntegerField(default=0)
		author = models.CharField(max_length=32, null=True)

		def __unicode__(self):
			return self.title

blogapp/forms.py
#coding:utf-8

from django import forms

class VoteTitle(forms.Form):

	# vote_title = forms.CharField(label="title",min_length=5, error_messages={"required":"必填",})
	vote_title = forms.ChoiceField(choices=[
		('title','tilte'),('标题1','标题1'),('标题2','title2') #元组第二个值为前端显示效果，第一个为后端实际存储
	])

class Userlogin(forms.Form):

	username = forms.CharField(label="用户名",required=True,min_length=1,max_length=10, widget=forms.TextInput(attrs={'placeholder':'用户名'}))
	passwd = forms.CharField(label="密码",required=True, min_length=1, max_length=10,widget=forms.TextInput(attrs={'placeholder':'密码'}))

class UserReg(forms.Form):

	username = forms.CharField(label="用户名",required=True,min_length=1,max_length=10)
	passwd = forms.CharField(label="密码",required=True, min_length=1, max_length=10)
	passwd_check = forms.CharField(label="密码确认",required=True, min_length=1, max_length=10)

class Article(forms.Form):

	title = forms.CharField(label="标题", required=True, max_length=48,widget=forms.TextInput(attrs={'placeholder':"标题"}))
	content = forms.CharField(label="内容", widget=forms.Textarea())

blogapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os

from django.http import HttpResponse, HttpResponseRedirect, Http404, StreamingHttpResponse
from django.shortcuts import render
from . import models
# from django.core.urlresolvers import  reverse
from django.urls import reverse
from . import forms
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required



# Create your views here.


def index(Request):
	return HttpResponse('hello')

@login_required #setting 中设置变量LOGIN_URL = '/login/',不使用装饰器可通过request.user.is_authenticate()判断
def homepage(Request):
	userinfo = {}
	userinfo['username'] = Request.user.username
	userinfo['status'] = True
	title_obj = forms.VoteTitle()
	articles = models.Article.objects.all()
	return render(Request, 'blogapp/homepage.html', {'articles': articles,'title_obj':title_obj,'userinfo':userinfo})


def articlepage(request, article_prikey):
	if request.method == "POST":
		article = models.Article.objects.get(pk=article_prikey)
		article.counter += 1
		article.save()
		return HttpResponseRedirect(reverse('blog:article_page', args=(article_prikey,)))
	else:
		article = models.Article.objects.get(pk=article_prikey)
		return render(request,'blogapp/article_page.html',{'article':article})

def myArticle(request):
	if request.method == "POST":
		print('nonononon!')
		article = forms.Article(request.POST)
		if article.is_valid():
			title = article.cleaned_data['title']
			content = article.cleaned_data['content']
			author = request.user.username
			models.Article.objects.create(title=title, content=content, author=author)
			return HttpResponseRedirect(reverse('blog:myArticle'))
	else:
		articles = models.Article.objects.filter(author=request.user.username)
		articleform = forms.Article()
		return render(request, 'blogapp/myArticle.html', {'articles':articles,'articleform':articleform})

def editArticle(request, article_prikey):
	article = models.Article.objects.get(author=request.user.username, pk=article_prikey)
	if article:
		if request.method == "POST":
			# article.title = request.POST['title']
			article.content = request.POST['content']
			article.save()
			return HttpResponse("修改成功哦")
		else:
			article_form = forms.Article()
			return render(request, 'blogapp/editarticle.html', {'article':article, 'article_form':article_form})
	else:
		raise Http404('访问的内容不存在')




def test_page(Request, num):
	return HttpResponse('this is test page:%s' % (num))

def vote_all_result(request):
	errors_obj = " "
	if request.method == "POST":
		form_post = forms.VoteTitle(request.POST)
		if form_post.is_valid():
			title = form_post.cleaned_data['vote_title'] #is_valid 返回true后，post的值保存在cleaned_data 中以字典形式
			article = models.Article.objects.get(pk=title)
			article.counter += 1
			article.save()
		else:
			# print 'error'
			errors_obj = form_post.errors
			# print form_post.errors["vote_title"]
			# print form_post.errors["vote_title"][0]
			# print type(form_post.errors["vote_title"])
	title_obj = forms.VoteTitle(
		initial={'vote_title':'标题1'} #列表默认值
	)
	articles = models.Article.objects.all()
	return HttpResponseRedirect(reverse('blog:homepage'))

def upload_file(request):
	articles = models.Article.objects.all()
	if request.method == "POST":
		# print type(request.FILES['file']), len(request.FILES['file']),dir(request.FILES['file'])
		handle_upload_file(request.FILES['file'], str(request.FILES['file']))
		return HttpResponse('success')

def handle_upload_file(file, name):
	path = '/home/upload/'
	if not os.path.exists(path):
		os.mkdir(path)
	with open(os.path.join(path, name), 'wb+') as destination:
		for chunk in file.chunks():
			print(len(chunk))
			destination.write(chunk)



def download(request, file):
	root_download_path = '/home/download/'
	request_download_path = request.path.replace('/download/','')
	download_path = os.path.join(root_download_path, request_download_path)
	if os.path.exists(download_path):
		if os.path.isdir(download_path):
			dir_list = [ (os.path.join(request_download_path, name), name) for name in os.listdir(download_path) if os.path.isdir(os.path.join(download_path,name)) ]
			file_list = [ (os.path.join(request_download_path, name), name, os.path.getsize(download_path)) for name in os.listdir(download_path) if os.path.isfile(os.path.join(download_path,name)) ]
			return render(request, 'blogapp/download_page.html', {'dir_list':dir_list,'file_list':file_list})
		else:
			response = StreamingHttpResponse(readFile(download_path))
			response['Content-Type'] = 'multipart/form-data'
			response['Content-Disposition'] ='attachment;filename="{0}"'.format(file)
			return response

	else:
		raise Http404('file not exist')

def readFile(filename, chunk_size=512):
	with open(filename, 'rb') as f:
		while True:
			c = f.read(chunk_size)
			print(len(c))
			if c:
				yield c
			else:
				break



def login(request):
	if request.method == 'POST':
		form = forms.Userlogin(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			passwd = form.cleaned_data['passwd']
			user = authenticate(username=username, password=passwd)
			print(type(user))
			userinfo = forms.Userlogin()
			if user:
				# if request.session.has_key('IS_LOGIN'):
				if request.session.has_key('username'):
					if request.session['username'] == username:
						context = {'tips':"用户已经登录，请勿重复登录"}
						return render(request, 'blogapp/login.html', {'userinfo':userinfo,'context':context})
				request.session['username'] = username
				auth.login(request, user)
				return HttpResponseRedirect(reverse('blog:homepage'))
				# else:
				# 	request.session['IS_LOGIN'] = True
				# 	request.session['username'] = username
				# 	auth.login(request, user)
				# 	return HttpResponseRedirect(reverse('blog:homepage'))
			else:
				context = {'isLogin':False,'passwd':False,'tips':"用户不存在或密码错误"}
				return render(request, 'blogapp/login.html', {'userinfo':userinfo,'context':context})
		else:
			userinfo = forms.Userlogin()
			errors =  form.errors
			context = {'isLogin':False,'passwd':False}
			return render(request, 'blogapp/login.html', {'errors':errors, 'userinfo':userinfo})
	else:
		userinfo = forms.Userlogin()
		# print(userinfo)
		return render(request,'blogapp/login.html',{'userinfo':userinfo})

def register(request):
	context = {}
	if request.method == "POST":
		form = forms.UserReg(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			passwd = form.cleaned_data['passwd']
			# user = auth.authenticate(username=username, password=passwd)
			# if user:
			if User.objects.filter(username=username):
				context['msg'] = '用户名存在'
				context['userinfo'] = forms.UserReg()
				return render(request, 'blogapp/register.html', context)
			user = User.objects.create_user(username=username, password=passwd)
			user.save()
			auth.login(request, user)
			return HttpResponseRedirect(reverse('blog:homepage'))
	else:
		# context = {'isLogin':False}
		userinfo = forms.UserReg()
		# print(userinfo)
		return render(request, 'blogapp/register.html', {'userinfo':userinfo})

def logout(request):
	auth.logout(request)
	return HttpResponseRedirect(reverse('blog:homepage'))

@login_required()
def chatroom(Request):
	username = Request.user.username
	return render(Request, 'blogapp/chatroom.html',{'username':username})

blogapp/templates/blogapp/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ArticlePage</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br/>
<h2>{{ article.content }}</h2>
<br/>
<h3>{{ article.release_time }}</h3>
<br/>
<h4>{{ article.counter }}</h4>
<br/>
<form action="{% url 'blog:vote' article.title %}" method="post">
    {% csrf_token %}
    <label for="sub">提交</label>
    <input type="submit" id="sub" value="提交" />
</form>
{#<a href="">赞</a>#}
</body>
</html>

blogapp/templates/blogapp/chatroom.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Web Socket</title>
</head>
<script type="text/javascript">
var ws
var username = "{{ username }}"
function startWS() {
    console.log('start once again');
//    ws = new WebSocket("ws://echo.websocket.org");
    ws = new WebSocket("ws://127.0.0.1:9999")
    ws.onopen = function (msg) {
        console.log('websocket opened');
    }
    ws.onmessage = function (message) {
        document.getElementById("view").value += username + ":" + message.data + "\n";
        console.log('websocket msg');
    }
    ws.onerror = function (error) {
        console.log('websocket error');
    }
    ws.onclose = function () {
        ws.send('websocket closed');
    }
}
function sendMessage() {
    var input = document.getElementById("chat");
    ws.send(input.value);
}
</script>
<body onload="startWS()">
{#<button onclick="startWS()">创建websocket</button><br>#}
<textarea cols="20" rows="5" name="view" id="view" readonly></textarea><br>
<input type="text" name="chat" id="chat" onkeydown="if(event.keyCode==13) {sendMessage()}">
<button onclick="sendMessage()" ">发送消息</button>
</body>
</html>

blogapp/templates/blogapp/download_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>下载</title>
</head>
<body>
<table board="1">
    <tr>
        <th>名称</th>
        <th>大小</th>
    </tr>
    {% for name in dir_list %}
        <tr>
            <td><a href="{% url 'download' name.0 %}">{{ name.1 }}</a></td>
        </tr>
    {% endfor %}
    {% for name in file_list %}
        <tr>
            <td><a href="{% url 'download' name.0 %}">{{ name.1 }}</a></td>
            <td>{{ name.2 }}</td>
        </tr>
    {% endfor %}
</table>
</body>
</html>

blogapp/templates/blogapp/editarticle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑</title>
</head>

<body>
<form action="{% url 'blog:editArticle' title %}" accept-charset="UTF-8" method="post">
    {% csrf_token %}
    {{ article_form.as_ul }}
    <input type="submit" value="确定修改">
</form>
<script type="text/javascript">
var title = "{{ article.title }}";
var content = "{{ article.content }}";
function loadtext() {
    document.getElementById('id_title').value = title;
    document.getElementById('id_content').value = content;
}
window.onload = loadtext();
</script>
</body>
</html>

blogapp/templates/blogapp/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
{#<script type="text/javascript">#}
{#    function test(){#}
{#        title = document.getElementById("title").value;#}
{#        alert(title);#}
{#    }#}
{#</script>#}
<body>
    {{ user_status.status }}
    {{ user_status.username }}
    {% if userinfo.status == True %}
        {{ userinfo.username }}
        <a href="{% url 'logout' %}">注销</a>
    {% endif %}
    {% if userinfo.status != True  %}
        <a href="{% url 'login' %}">登录</a>
    {% endif %}

    <h1>上传文件</h1>
        <form action="{% url 'blog:upload' %}" role="form" method="post" enctype="multipart/form-data" accept-charset="utf-8">
            {% csrf_token %}
            <input type="file" name="file">
            <input type="submit" value="上传">
        </form>
    <h1><a href="{% url 'download' '' %}">下载文件</a></h1>
    <h1><a href="{% url 'chatroom' %}" >聊天室</a></h1>
    <a href="{% url 'blog:myArticle' %}">个人</a>


</body>
</html>

blogapp/templates/blogapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
    <form action="{% url 'login' %}" method="post" accept-charset="UTF-8" enctype="multipart/form-data">
        {% csrf_token %}
        {{ userinfo.username }}
        {{ userinfo.passwd}}
        {{ context.tips }}
        <input type="submit" value="登录">
    </form>
</body>
</html>

blogapp/templates/blogapp/myArticle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人中心</title>
</head>
<body>
{% for article in articles %}
    {{ article.release_time }}
    {{ article.title }}
    <a href="{% url 'blogapp:editArticle' article.title %}">编辑</a></br>
{% endfor %}
<form action="{% url 'blogapp:myArticle' %}" method="post" accept-charset="UTF-8">
    {% csrf_token %}
    {{ articleform.as_ul }}
    <input type="submit" value="提交">
</form>

</body>
</html>

blogapp/templates/blogapp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
    <form action="{% url 'register' %}" method="post" accept-charset="UTF-8" enctype="multipart/form-data">
        {% csrf_token %}
        {{ userinfo.as_ul}}
        {{ msg }}

        <input type="submit" value="注册">
    </form>
</body>
</html>